// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyEn0vKEiGrxoIfn4dPGtWWKJCJIWASck',
    appId: '1:592182452972:web:3d153e7077b7d63efffbc9',
    messagingSenderId: '592182452972',
    projectId: 'letsspeak-9a2ea',
    authDomain: 'letsspeak-9a2ea.firebaseapp.com',
    storageBucket: 'letsspeak-9a2ea.appspot.com',
    measurementId: 'G-EF4MLQCFB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDDs7gXKeYadoBPkpGVD5-ctLWV5sFyg',
    appId: '1:592182452972:android:92ff147eaaf94416fffbc9',
    messagingSenderId: '592182452972',
    projectId: 'letsspeak-9a2ea',
    storageBucket: 'letsspeak-9a2ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGAjKlHgh0yxpKBRJtsI0YQa0gQiO6UIk',
    appId: '1:592182452972:ios:0b01969cd5f6f6ddfffbc9',
    messagingSenderId: '592182452972',
    projectId: 'letsspeak-9a2ea',
    storageBucket: 'letsspeak-9a2ea.appspot.com',
    androidClientId: '592182452972-qbqu5nh9279kjifmi200nuiivuulpmu2.apps.googleusercontent.com',
    iosClientId: '592182452972-9jkpggefhclhapqdoqdk3bhlfnc72bm9.apps.googleusercontent.com',
    iosBundleId: 'dev.quannq.letsspeak',
  );
}
