// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPn90KRrsn7hOmLm8TwrqrN3zFTJq6eY',
    appId: '1:632062248862:web:295d5d012854f7d639b88f',
    messagingSenderId: '632062248862',
    projectId: 'itutor-9f1fe',
    authDomain: 'itutor-9f1fe.firebaseapp.com',
    storageBucket: 'itutor-9f1fe.appspot.com',
    measurementId: 'G-XGSER4JQJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXG_EmSQCQXGjogG61GJalgwSs65BaEcw',
    appId: '1:632062248862:android:3d5cd3c28d8046e839b88f',
    messagingSenderId: '632062248862',
    projectId: 'itutor-9f1fe',
    storageBucket: 'itutor-9f1fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYjlilFnaGcrI8d63UfrtUI8ZyLrR1NV4',
    appId: '1:632062248862:ios:b5d6d5b6b24d7bbb39b88f',
    messagingSenderId: '632062248862',
    projectId: 'itutor-9f1fe',
    storageBucket: 'itutor-9f1fe.appspot.com',
    androidClientId: '632062248862-7ptr53nh0aer9pjg82khqk60hoplut4s.apps.googleusercontent.com',
    iosClientId: '632062248862-0fiqqacjivpa28pmohigacm2t8c6ed92.apps.googleusercontent.com',
    iosBundleId: 'dev.quannq.speakout',
  );
}
